spring:
  application:
    name: producer-demo
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848

server:
  port: 10001

producer-age: 22